{{- if .Values.useCertManager }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.cert-manager.name }}
  namespace: {{ .Values.rootNamespace }}
spec:
  acme:
    email: {{ .Values.cert-manager.email }}
    server: {{ .Values.cert-manager.apiServer }}
    privateKeySecretRef:
      name: {{ .Values.cert-manager.secretKeyName }}
    solvers:
      - http01:
          ingress:
            class: public
{{- end }}