{{- if .Values.registryAuthRequired }}
kind: Secret
type: kubernetes.io/dockerconfigjson
apiVersion: v1
metadata:
  name: dockerconfigjson-github-com
  namespace: msgmate-io-prod
stringData:
  .dockerconfigjson: {{ .Values.prod.dockerconfigjson }}
{{- end }}