# Generated by Django 4.1.2 on 2023-04-29 18:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='hash',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='base_language',
            field=models.CharField(choices=[('english', 'English'), ('german', 'German'), ('spanish', 'Spanish'), ('french', 'French'), ('italian', 'Italian'), ('dutch', 'Dutch'), ('portuguese', 'Portuguese'), ('russian', 'Russian'), ('japanese', 'Japanese'), ('korean', 'Korean'), ('arabic', 'Arabic'), ('turkish', 'Turkish'), ('swedish', 'Swedish'), ('polish', 'Polish'), ('danish', 'Danish'), ('norwegian', 'Norwegian'), ('finnish', 'Finnish'), ('greek', 'Greek'), ('czech', 'Czech'), ('hungarian', 'Hungarian'), ('romanian', 'Romanian'), ('indonesian', 'Indonesian'), ('hebrew', 'Hebrew'), ('thai', 'Thai'), ('vietnamese', 'Vietnamese'), ('ukrainian', 'Ukrainian'), ('slovak', 'Slovak'), ('croatian', 'Croatian'), ('serbian', 'Serbian'), ('bulgarian', 'Bulgarian'), ('lithuanian', 'Lithuanian'), ('latvian', 'Latvian'), ('estonian', 'Estonian'), ('persian', 'Persian'), ('afrikaans', 'Afrikaans'), ('swahili', 'Swahili')], default='english', max_length=255),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='language',
            field=models.CharField(choices=[('english', 'English'), ('german', 'German'), ('spanish', 'Spanish'), ('french', 'French'), ('italian', 'Italian'), ('dutch', 'Dutch'), ('portuguese', 'Portuguese'), ('russian', 'Russian'), ('japanese', 'Japanese'), ('korean', 'Korean'), ('arabic', 'Arabic'), ('turkish', 'Turkish'), ('swedish', 'Swedish'), ('polish', 'Polish'), ('danish', 'Danish'), ('norwegian', 'Norwegian'), ('finnish', 'Finnish'), ('greek', 'Greek'), ('czech', 'Czech'), ('hungarian', 'Hungarian'), ('romanian', 'Romanian'), ('indonesian', 'Indonesian'), ('hebrew', 'Hebrew'), ('thai', 'Thai'), ('vietnamese', 'Vietnamese'), ('ukrainian', 'Ukrainian'), ('slovak', 'Slovak'), ('croatian', 'Croatian'), ('serbian', 'Serbian'), ('bulgarian', 'Bulgarian'), ('lithuanian', 'Lithuanian'), ('latvian', 'Latvian'), ('estonian', 'Estonian'), ('persian', 'Persian'), ('afrikaans', 'Afrikaans'), ('swahili', 'Swahili')], default='english', max_length=50),
        ),
    ]
