# Generated by Django 4.1.2 on 2023-04-29 19:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_chatmessage_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='ai_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
