# Generated by Django 4.1.2 on 2023-04-29 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_project_ai_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
